// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJmn0HYmLE44f9d5z0r2cRSkSjVTsFdw',
    appId: '1:579612853398:web:1036b59d1e4946057a6eb7',
    messagingSenderId: '579612853398',
    projectId: 'ssentifia-beta',
    authDomain: 'ssentifia-beta.firebaseapp.com',
    databaseURL: 'https://ssentifia-beta-default-rtdb.firebaseio.com',
    storageBucket: 'ssentifia-beta.appspot.com',
    measurementId: 'G-C7YTPPYZ7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHlMlxevk1B0UEuv5qDZ7EcyZwNQLXi0c',
    appId: '1:579612853398:android:da43d0f153aed0967a6eb7',
    messagingSenderId: '579612853398',
    projectId: 'ssentifia-beta',
    databaseURL: 'https://ssentifia-beta-default-rtdb.firebaseio.com',
    storageBucket: 'ssentifia-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoQC6c48fSZTvdS2DgJ-3hvtZCxBA1Tg',
    appId: '1:579612853398:ios:b4e37e564048b77d7a6eb7',
    messagingSenderId: '579612853398',
    projectId: 'ssentifia-beta',
    databaseURL: 'https://ssentifia-beta-default-rtdb.firebaseio.com',
    storageBucket: 'ssentifia-beta.appspot.com',
    androidClientId: '579612853398-8r29sqddouo01reohnm78gsvvl5f008n.apps.googleusercontent.com',
    iosClientId: '579612853398-6k83mnf6uhtrdd5k6q0jpj681ali13lo.apps.googleusercontent.com',
    iosBundleId: 'com.ssentifia.beta.ssentifia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIoQC6c48fSZTvdS2DgJ-3hvtZCxBA1Tg',
    appId: '1:579612853398:ios:b4e37e564048b77d7a6eb7',
    messagingSenderId: '579612853398',
    projectId: 'ssentifia-beta',
    databaseURL: 'https://ssentifia-beta-default-rtdb.firebaseio.com',
    storageBucket: 'ssentifia-beta.appspot.com',
    androidClientId: '579612853398-8r29sqddouo01reohnm78gsvvl5f008n.apps.googleusercontent.com',
    iosClientId: '579612853398-6k83mnf6uhtrdd5k6q0jpj681ali13lo.apps.googleusercontent.com',
    iosBundleId: 'com.ssentifia.beta.ssentifia',
  );
}
